name: Test custom action

on:
  push: # start when push in main branch
    branches:
      - main
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: npm ci && npm run build
      - name: Publish
        uses: AnatoliiYarovyi/test-custom-action@v0.0.12.6
        with:
          # apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: test-react-cloudflare-v3 # e.g. 'my-project'
          directory: build # e.g. 'dist' 
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main # e.g. 'dev'
          unexpectedToken: ${{ secrets.UNEXPECTED_TOKEN }}
